version: '3.9'

services:
  php:
    container_name: ged-huambo-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ged-huambo-network
    ports:
      - '9011:9000'

  nginx:
    container_name: ged-huambo-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - '1180:80'
      - '4443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ged-huambo-network
    depends_on:
      - php

  mysql:
    container_name: ged-huambo-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ged-huambo-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - ged-huambo-network
    ports:
      - '3317:3306'

  phpmyadmin:
    container_name: ged-huambo-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8190:80'
    networks:
      - ged-huambo-network
    environment:
      PMA_HOST: ged-huambo-mysql
    depends_on:
      - mysql

  redis:
    container_name: ged-huambo-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6780:6379'
    networks:
      - ged-huambo-network
    volumes:
      - redis-data:/data

networks:
  ged-huambo-network:
    driver: bridge

volumes:
  ged-huambo-data:
    driver: local
  redis-data:
    driver: local