version: '3.9'

services:
  php:
    container_name: keepcomply-QA-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - keepcomply-QA-network
    ports:
      - '9070:9000'  # PHP-FPM

  nginx:
    container_name: keepcomply-QA-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - '9080:80'
      - '9443:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - keepcomply-QA-network
    depends_on:
      - php

  mysql:
    container_name: keepcomply-QA-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - keepcomply-QA-data:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - keepcomply-QA-network
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: nf
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: nf@204

  phpmyadmin:
    container_name: keepcomply-QA-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '9081:80'
    networks:
      - keepcomply-QA-network
    environment:
      PMA_HOST: keepcomply-QA-mysql
    depends_on:
      - mysql

  redis:
    container_name: keepcomply-QA-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - '6380:6379'
    networks:
      - keepcomply-QA-network
    volumes:
      - redis-data:/data

networks:
  keepcomply-QA-network:
    driver: bridge

volumes:
  keepcomply-QA-data:
    driver: local
  redis-data:
    driver: local
