<?php

namespace Database\Seeders\SolSeguros;

use App\Models\Indicator\IndicatorType as IndicatorIndicatorType;
use Illuminate\Database\Seeder;

class AgenteProdutorSeeder extends Seeder
{
    public function run()
    {
        /**IndicatorType */
        $IndicatorType = [
            ['description' => 'Dependencia Do Lubango', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência do Huambo(1201)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Luena', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Dundo(lunda Norte)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'SEDE SOL SEGUROS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Edificio Sol', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Cabinda(101)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependência da Ganda(1110)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Lobito(1101)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência da Quibala(601)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Namibe', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Soyo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia De Ndalatando', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Benfica II(532)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Posto Do Mercado Municipal Do Namibe', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Uige', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Inss Do Mbanza Congo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Sumbe', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência da Huíla (Lubango)(1501)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Caxito (701)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia De Saurimo(lunda Sul)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Menongue(1301)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Porto De Luanda(024)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Posto Do Luau(luanas - Moxico)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Menongue II', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Mbanza Congo (201)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Viana Estrada De Catete(524)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia De Malanje', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Benguela(1102)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependência de Porto Amboim(1402)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência do Cuito(1601)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependência do Lobito II(1111)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Maculusso(503)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agência de Ondjiva(1701)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Posto Atendimento De Caculama', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependência do Calulo(602)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Samba(530)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Prenda', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Kilamba I(535)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Talatona(536)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Posto Do Luvo(mbanza Congo)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Agencia Do Aeroporto De Luanda', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Cazenga(506)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Mutamba(502)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Cacuaco(510)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Largo Das Heroinas(504)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Viana Estalagem(507)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Via Expresso(515)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Caxito II(702)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Ginga Shopping(534)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Viana Vila(513)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Santa Clara', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Ndalatando II(802)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Malanje II(902)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Dundo II(1902)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Saurimo II(1802)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Luena II(2002)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Cuito II(1602)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Huambo II(1202)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Namibe II(1002)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Ondjiva II(1702)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Lubango II(1502)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Benguela II(1107)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Cabinda II(102)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Soyo II(203)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Catumbela(1105)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Porto Do Lobito(1104)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Centralidade Do Lossambo(1203)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Universidade Mandume(1504)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Palanca(537)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Sequele(538)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Kinaxixi(539)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Chibia(1503)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Xangongo(1703)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Porto Do Namibe(1003)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Calandula(903)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Nzeto(202)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Bailundo(1204)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Caala(1205)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Lucapa(1903)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Luano(1904)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Cubal(1108)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Ganda II(1109)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Gabela(1403)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Cela(waku Kungo)(1404)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Camabatela(803)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Kibala II(603)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Negage(302)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Sanza Pombo(303)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia De Maquela Do Zombo(304)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Luanda Sul(540)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Ilha De Luanda(541)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Vila Alice(542)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Comarca Do Luanda(543)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Nova Vida(544)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Patriota(545)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Miramar(546)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Grafanil(547)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Zango Iii(548)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Kapalanga(549)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Zango Zero(550)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Camama(551)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Centralidade Do 5000(552)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Morro Bento(553)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Centralidade Do Capari(703)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Km 30(554)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Panguila(704)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Rocha Pinto(555)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Golfe Ii(556)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Sao Paulo(557)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Hoji Ya Henda(558)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Sambizanga(559)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Centralidade Do Km 44(560)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Gamek(561)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Cuca(562)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Ngola Kiluanje(563)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Maculusso Ii(564)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Cruzeiro(565)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Marginal(566)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Alvalade(567)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do Maianga(568)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Sagrada Familia(569)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Do 1º De Maio(570)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
            ['description' => 'Dependencia Da Lixeira(571)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 11],
        ];

        // Inserindo os indicadores de agência/canal caso não existam no banco
        foreach ($IndicatorType as $value) {
            if (!IndicatorIndicatorType::where('description', $value['description'])->where('indicator_id', 11)->exists()) {
                IndicatorIndicatorType::create($value);
            }
        }
    }
}