<?php

namespace Database\Seeders\nossaSeguros;

use App\Models\Indicator\IndicatorType as IndicatorIndicatorType;
use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class CAESeed extends Seeder
{
    public function run()
    {
        /**IndicatorType */
        $IndicatorType = [
            [
                'description' => 'CEREALICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE ALGODÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE PLANTAS OLEAGINOSAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE CANA DE AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE TABACO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE MANDIOCA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA DE SISAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTRAS CULTURAS AGRÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'HORTICULTURA, ESPECIALIDADES HORTÍCOLAS E PRODUTOS VIVEIRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SEGURO DE AGRICULTURA (GENÉRICO)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SEDE AGRICULTURA (AVENÇA)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CAFEICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FRUTICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'VITICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CULTURA PLANTAS P/PREPARAÇÃO DE ESPECIARIAS E BEBIDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'BOVINOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CRIAÇÃO DE GADO OVINO, CAPRINO, CAVALAR, ASININO E MUAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SUINICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'AVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'APICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CRIAÇÃO DE OUTROS ANIMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SILVICULTURA, ROÇAGEM DE MATO, SURRIBAS E SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ARRANQUE E CORTE DE ÁRVORESIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTRAS ACTIVIDADES FLORESTAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CAÇA, REPOVOAMENTO E ACTIVIDADES RELACIONADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESCA MARÍTIMA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESCA EM ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'APANHA DE ALGAS E DE OUTROS PRODUTOS DO MAR/ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'VIVEIROS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PISCICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE CARVÃO',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E AGLOMERAÇÃO DE LINHITE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E AGLOMERAÇÃO DE TURFA',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE PETRÓLEO BRUTO E GÁS NATURAL',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ACTIVIDADES RELACIONADAS COM A EXTRACÇÃO DE PETRÓLEO E GÁS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE MINÉRIOS DE URÂNIO E TORIO',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS DE FERRO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS DE COBRE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS DE METAIS PRECIOSOS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS METÁLICOS NÃO FERROSOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE PEDRA (SEM EMPREGO DE EXPLOSIVOS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE PEDRA (COM EMPREGO DE EXPLOSIVOS)',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE CALCÁRIO, GESSO E CRÊ',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAIBRO E AREIA',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE ARGILA E CAULINO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE MINERAIS P/INDÚSTRIA QUÍMICA E DE ADUBOS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAL MARINHO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAL GEMA',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'REFINAÇÃO DO SAL',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EXTRACÇÃO DE MINÉRIOS METÁLICOS A CEU ABERTO',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ABATE DE GADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ABATE DE AVES E OUTROS ANIMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE PRODUTOS À BASE DE CARNE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUTOS DA PESCA E DE AQUACULTURA (FABRICO E CONGELAÇÃO)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSERVAS DE PEIXE E OUTROS PRODUTOS DE PESCA',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SECAGEM, SALGA E TRANSFORMAÇÃO PRODUTOS DA PESCA/AQUACULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO E CONGELAÇÃO DE SUMOS DE FRUTOS E PROD. AGRICOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE DOCES, COMPOTAS, GELEIAS E MARMELADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO E REFINAÇÃO DE MARGARINAS, ÓLEOS E GORDURAS ALIMENT.',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DE LEITE E DERIVADOS (LACTICINIOS, IOGURTES, ETC.)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICAÇÃO DE GELO, GELADOS E SORVETES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'MOAGEM, DESCASQUE E PREPARAÇÃO DE CEREAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE AMIDOS FÉCULAS E PRODUTOS AFINS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'RAÇÕES PARA ANIMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PANIFICAÇÃO E AFINS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CACAU, DO CHOCOLATE E DOS PRODUTOS DE CONFEITAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MASSAS ALIMENTÍCIAS, CUSCUS E SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CAFÉ E DO CHÁ',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS ALIMENTARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ALCOOL E BEBIDAS ALCOÓLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE VINHOS, VINAGRES E BEBIDAS FERMENTADAS DE FRUTOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE CERVEJA E MALTE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENGARRAFAMENTO DE ÁGUAS MINERAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE REFRIGERANTES E OUTRAS BEBIDAS NÃO ALCOÓLICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO TABACO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, FIAÇÃO E TECELAGEM DE ALGODÃO E FIBRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE LINHAS DE COSTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ACABAMENTO DE TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TAPETES E CARPETES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE CORDOARIA E REDES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE BORDADOS E RENDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS ARTIGOS TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TECIDOS E ARTIGOS DE MALHA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Confecção de outro vestuário exterior por medida',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESTOFOS E COLCHOARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, CURTIMENTA E ACABAMENTOS DE COURO E PELES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE MALAS, PASTAS E OUTROS EM COURO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE COMPONENTES PARA CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            // Itens da imagem image_ad348f.png
            [
                'description' => 'INDÚSTRIA DO AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CACAU, DO CHOCOLATE E DOS PRODUTOS DE CONFEITAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MASSAS ALIMENTÍCIAS, CUSCUS E SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CAFÉ E DO CHÁ',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS ALIMENTARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ALCOOL E BEBIDAS ALCOÓLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE VINHOS, VINAGRES E BEBIDAS FERMENTADAS DE FRUTOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE CERVEJA E MALTE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENGARRAFAMENTO DE ÁGUAS MINERAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE REFRIGERANTES E OUTRAS BEBIDAS NÃO ALCOÓLICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO TABACO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, FIAÇÃO E TECELAGEM DE ALGODÃO E FIBRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE LINHAS DE COSTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => '17120 ACABAMENTO DE TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TAPETES E CARPETES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE CORDOARIA E REDES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE BORDADOS E RENDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS ARTIGOS TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TECIDOS E ARTIGOS DE MALHA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Confecção de outro vestuário exterior por medida',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESTOFOS E COLCHOARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, CURTIMENTA E ACABAMENTOS DE COURO E PELES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE MALAS, PASTAS E OUTROS EM COURO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE COMPONENTES PARA CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],

            // Itens da imagem image_ad34ed.png
            [
                'description' => 'FABRICO DE CALÇADO EM MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SERRAÇÃO E APLAINAMENTO DA MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE FOLHEADOS, AGLOMERADOS E CONTRAPLACADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ARTIGOS DE CARPINTARIA PARA A CONSTRUÇÃO CIVIL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE EMBALAGENS, CAIXÕES E OUTROS ARTIGOS EM MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
       
            [
                'description' => 'FABRICO DE ARTIGOS DE CORTIÇA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MOBILIÁRIO DE MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE VASSOURAS, ESCOVAS E PINCEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PAPEL, CARTÃO E EMBALAGENS DE CARTÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ARTIGOS DE PAPEL P/USO DOMÉSTICO E SANITÁRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EDIÇÃO DE LIVROS, JORNAIS, REVISTAS E OUTRAS PUBLICAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EDIÇÃO DE GRAVAÇÕES DE SOM',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTRAS EDIÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'IMPRESSÃO TIPOGRÁFICA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'REPRODUÇÃO DE SUPORTES GRAVADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE COQUE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUTOS PETROLÍFEROS REFINADOS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRATAMENTO DE COMBUSTÍVEL NUCLEAR',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE GASES INDUSTRIAIS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS QUÍMICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ADUBOS, PESTICIDAS E COMPOSTOS AZOTADOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO TINTAS, VERNIZES, LACAS, COLAS, CERAS E GRAXAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PRODUTOS FARMACEUTICOS E DE USO MEDICINAL',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE SABÕES, DETERGENTES, PRODUTOS LIMPESA, POLIMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PERFUMES, COSMÉTICOS E PRODUTOS DE HIGIENE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE EXPLOSIVOS, ARTIGOS DE PIROTECNIA E FOSFOROS',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PNEUS E DE CÂMARAS-DE-AR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'RECONSTRUÇÃO, VULCANIZAÇÃO E RECAUCHUTAGEM DE PNEUS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS DE BORRACHA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            // Itens da imagem image_ad348f.png
            [
                'description' => 'INDÚSTRIA DO AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CACAU, DO CHOCOLATE E DOS PRODUTOS DE CONFEITAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MASSAS ALIMENTÍCIAS, CUSCUS E SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO CAFÉ E DO CHÁ',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS ALIMENTARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ALCOOL E BEBIDAS ALCOÓLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE VINHOS, VINAGRES E BEBIDAS FERMENTADAS DE FRUTOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE CERVEJA E MALTE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENGARRAFAMENTO DE ÁGUAS MINERAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE REFRIGERANTES E OUTRAS BEBIDAS NÃO ALCOÓLICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INDÚSTRIA DO TABACO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, FIAÇÃO E TECELAGEM DE ALGODÃO E FIBRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE LINHAS DE COSTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => '17120 ACABAMENTO DE TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TAPETES E CARPETES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE CORDOARIA E REDES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE BORDADOS E RENDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS ARTIGOS TÊXTEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TECIDOS E ARTIGOS DE MALHA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Confecção de outro vestuário exterior por medida',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESTOFOS E COLCHOARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PREPARAÇÃO, CURTIMENTA E ACABAMENTOS DE COURO E PELES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE MALAS, PASTAS E OUTROS EM COURO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE COMPONENTES PARA CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],

            // Itens da imagem image_ad34ed.png
            [
                'description' => 'FABRICO DE CALÇADO EM MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SERRAÇÃO E APLAINAMENTO DA MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE FOLHEADOS, AGLOMERADOS E CONTRAPLACADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ARTIGOS DE CARPINTARIA PARA A CONSTRUÇÃO CIVIL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE EMBALAGENS, CAIXÕES E OUTROS ARTIGOS EM MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
           
            [
                'description' => 'FABRICO DE ARTIGOS DE CORTIÇA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MOBILIÁRIO DE MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE VASSOURAS, ESCOVAS E PINCEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PAPEL, CARTÃO E EMBALAGENS DE CARTÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ARTIGOS DE PAPEL P/USO DOMÉSTICO E SANITÁRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EDIÇÃO DE LIVROS, JORNAIS, REVISTAS E OUTRAS PUBLICAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EDIÇÃO DE GRAVAÇÕES DE SOM',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTRAS EDIÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'IMPRESSÃO TIPOGRÁFICA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'REPRODUÇÃO DE SUPORTES GRAVADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE COQUE',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUTOS PETROLÍFEROS REFINADOS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRATAMENTO DE COMBUSTÍVEL NUCLEAR',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE GASES INDUSTRIAIS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS QUÍMICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ADUBOS, PESTICIDAS E COMPOSTOS AZOTADOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO TINTAS, VERNIZES, LACAS, COLAS, CERAS E GRAXAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PRODUTOS FARMACEUTICOS E DE USO MEDICINAL',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE SABÕES, DETERGENTES, PRODUTOS LIMPESA, POLIMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PERFUMES, COSMÉTICOS E PRODUTOS DE HIGIENE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE EXPLOSIVOS, ARTIGOS DE PIROTECNIA E FOSFOROS',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PNEUS E DE CÂMARAS-DE-AR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'RECONSTRUÇÃO, VULCANIZAÇÃO E RECAUCHUTAGEM DE PNEUS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS DE BORRACHA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],

            // Itens da imagem image_ad37f6.png
            [
                'description' => 'FABRICO DE CHAPAS, FOLHAS, TUBOS E PERFIS DE PLÁSTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS ARTIGOS DE PLÁSTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE VIDRO E ARTIGOS DE VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CORTE, ESPELHAGEM E LAPIDAÇÃO DE VIDRO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ARTIGOS CERÂMICOS, DE PORCELANA, FAIANÇA E BARRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE TIJOLOS, TELHAS E PRODUTOS BARRO P/ CONSTRUÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE CIMENTO, FIBROCIMENTO, BETÃO E GESSO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICAÇÃO DE CAL E GESSO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SERRAGEM, CORTE E ACABAMENTO DA PEDRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E TRANSFORMAÇÃO DE OUTROS MINERAIS NÃO METÁLICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'METALOMECÂNICAS E SERTRALHARIAS MECÂNICAS PESADAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FUNDIÇÃO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TREFILAGEM',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SERRALHARIA CIVIL (PORTAS, JANELAS, PORTAS E SIMILARES)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE RESARVATÓRIOS, CALDEIRAS, RADIADORES, GERADORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICAÇÃO DE CUTELARIA, FERRAMENTAS, FERRAGENS E SIMILARES',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE LATOARIA E EMBALAGENS METÁLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MOBILIÁRIO METÁLICO E ACESSÓRIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE OUTROS PRODUTOS METÁLICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO MATERIAL DE GUERRA EM FERRO OU AÇO (SEM EXPLOSIVOS)',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'RECICLAGEM DE SUCATA E DESPERDICIOS METÁLICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE PEÇAS E ACESSÓRIOS PARA MÁQUINAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE EQUIPAMENTO DE ELEVAÇÃO E MOVIMENTAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB/REPARAÇÃO DE OUTRAS MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB/REP DE MÁQUINAS E TRACTORES AGRICOLAS E P/ SILVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB/REP MÁQUINAS P/INDÚSTRIAS EXTRACTIVAS E CONSTRUÇÃO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ELECTRODOMÉSTICOS E APARELHOS DE USO DOMÉSTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE MÁQUINAS DE ESCRITÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB/REP DE MOTORES, COMPRESSORES, GERADORES, TRANSFORMADORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB E REP. APARELHOS DE AR CONDICIONADO E REFRIGERAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE MATERIAL DE ILUMINAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE OUTROS ARTIGOS ELÉCTRICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE COMPONENTES ELECTRÓNICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB E REP DE APARELHOS DE SOM, IMAGEM E TELECOMUNICAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB E REP DE MATERIAL MÉDICO CIRURGICO, OPTICO E ORTOPÉDICO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FAB E REP DE OUTROS EQUIPAMENTOS ELECTRÓNICOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE RELÓGIOS E MATERIAL DE RELOJOARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE REBOQUES E SEMI-REBOQUES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ACESSÓRIOS PARA A INDUSTRIA DE TRANSPORTES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSTRUÇÃO E REPARAÇÃO DE EMBARCAÇÕES DE RECREIO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSTRUÇÃO E REPARAÇÃO DE OUTRAS EMBARCAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE MATERIAL PARA CAMINHOS DE FERRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE AERONAVES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE VELOCIPEDES E MOTOCICLOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO E REPARAÇÃO DE OUTRO MATERIAL DE TRANSPORTE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'DESMANTELAMENTO DE VEÍCULOS (SUCATAS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE JOALHARIA, OURIVESARIA, BIJUTARIA E SIMILARES',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'LAPIDAÇÃO E POLIMENTO DE PEDRAS PRECIOSAS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE INSTRUMENTOS MUSICAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE ARTIGOS DE DESPORTO, JOGOS E BRINQUEDOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE BRINDES, CANETAS, ARTIGOS DE ESCRITÓRIO E OUTROS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE GUARDA-CHUVAS E GUARDA-SOIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FABRICO DE BOTÕES, ARTIGOS DE OSSO, MARFIM E CHIFRE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTRAS INDÚSTRIAS TRANSFORMADORAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO DE ELECTRICIDADE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRANSPORTE E DISTRIBUIÇÃO DE ELECTRICIDADE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PRODUÇÃO E DISTRIBUIÇÃO DE VAPOR DE ÁGUA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO DE ÁGUA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TERRAPLANAGENS, DRENAGENS, FUNDAÇÕES E CONTENÇÕES',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSTRUÇÃO DE ESTRADAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSTRUÇÃO GERAL DE EDIFÍCIOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENGENHARIA CIVIL E OBRAS PÚBLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'DEMOLIÇÃO E ABERTURA DE VALAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'INSTALAÇÃO ELECTRICA, CLIMATIZAÇÃO E CANALIZAÇÃO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRABALHOS CARPINTARIA E SERRALHARIA EM OBRAS DE CONSTRUÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ACABAMENTOS DE INTERIORES (ESTUCAGEM, PINTURA, PAVIMENTOS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'MONTAGEM/DESMONTAGEM ESTRUTURAS E COBERTURAS METÁLICAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'MANOBRADORES E CONDUTORES DE MÁQUINAS CONST. CIVIL (ALUGUER)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'OUTROS TRABALHOS AFECTOS À CONSTRUÇÃO CIVIL',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ABERTURA DE POÇOS SEM EXPLOSIVOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'EMPREGO DE EXPLOSIVOS',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SONDAGENS GEOLOGICAS E LEVANTAMENTOS TOPOGRÁFICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio de veículos automóveis',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Manutenção de veículos automóveis',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio de peças e acessórios para veículos automóveis',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio de motociclos, de suas peças e acessórios',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Manutenção e reparação de motociclos, de suas peças e acessó',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => '5 Comércio a retalho de combustíveis para veículos a motor',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso mat.-prima agríc./têxteis, animais e prod. semi-a',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso combustíveis, minérios, máquinas, embarc. e aero',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso madeira, mat. construção, art. p/lar, alimentaçã',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Agentes do comércio por grosso misto sem predominância',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso produtos agrícolas brutos e animais vivos',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso cereais, sementes, leguminosos e alimentos para',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso flores e plantas',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso animais vivos, de peles e couro, para animais',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => ' Comércio grosso tabaco em bruto',
                'risk' => 'Médio',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso produtos alimentares, bebidas e tabaco',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso fruta e produtos hortícolas',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso carne e produtos à base de carne',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso leite e derivados, ovos, azeite e óleos alimenta',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso bebidas',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso tabaco',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso café, açúcar, chá, cacau e especiarias',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso peixe, crustáceos e moluscos',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso outros produtos alimentares',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso têxteis, vestuário e calçado',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso têxteis e vestuário',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso calçado',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso outros bens de consumo',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso electrodomésticos, aparelhos de rádio e televisã',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso louças e vidros, porcelana e produtos de limpeza',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso perfumes, produtos higiene e produtos farmacêuti',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso artigos de papelaria, livros, revistas e jornais',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Outro comércio por grosso de bens de consumo',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso combustíveis líquidos, sólidos, gasosos e deriva',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso minérios e metais',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso madeiras em bruto e produtos derivados',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso mat.construção (excepto madeira) e equip. sanitá',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso ferragens e ferramentas de canalização e aquecim',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso outros bens intermédios, desperdícios e sucatas',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso produtos químicos',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso bens intermédios (não agrícolas), desperdícios e',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso máq./ferramentas p/construção, agric. e floresta',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso máquinas e material de escritório',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio grosso outras máq./equipamento p/indústria, Comércio e nave',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Outro comércio por grosso',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho em estabelecimentos não especializados',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho em supermercados e hipermercados',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho n/especializado, c/base alimentos, bebidas e ta',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho n/especializado, sem alimentos, bebidas e tabac',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho frutas e de produtos hortícolas',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho carne e de produtos à base de carne',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho peixe, crustáceos e moluscos',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho pão, produtos de pastelaria e confeitaria',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho bebidas',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho outros alimentos e tabaco, em estab. especializ',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho produtos farmacêuticos, médicos, cosméticos e h',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho têxteis, vestuário, calçado e artigos de couro',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho têxteis e vestuário',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho calçado e artigos de couro',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho electrodomésticos, artigos e equipamentos para',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho electrodomésticos, aparelho de rádio e televisã',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho mobiliário e artigos de iluminação',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho louças, cutelaria e similares para uso doméstic',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio a retalho de outros artigos para o lar',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho ferragens, tintas, vidros, sanitários, ladrilho',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho produtos novos em estabelecimentos especializad',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho livros, jornais e artigos de papelaria',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho máquinas e outro material para escritório',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho relógios e artigos de ourivesaria',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho combustíveis para uso doméstico',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho outros produtos novos n/ especificados',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho artigos em segunda mão em estabelecimentos',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho artigos em segunda mão fora de estabelecimentos',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho por correspondência',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'VENDEDORES AMBULANTES NA RUA, FEIRAS OU MERCADOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho em bancas e feiras de produtos alimentares e be',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho em bancas e feiras de produtos n/alimentares e',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Comércio retalho por outros métodos, não efectuado em estabeleci',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Reparação de calçado e outros artigos de couro',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Reparação de electrodomésticos',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Reparação de relógios e artigos de joalharia',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Reparação de bens pessoais e domésticos',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'VIDRARIAS E VIDRACEIROS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'COMERCIO DE FERRO VELHO E SUCATAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'COMERCIO DE OUTROS PRODUTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESTUDIOS FOTOGRÁFICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'HOTÉIS, PENSÕES, RESIDENCIAIS E DEMAIS EST. HOTELEIROS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PARQUES DE CAMPISMO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'RESTAURANTES, CAFÉS, SNACKS, CERVEJARIAS, PASTELARIAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENTREGA DE REFEIÇÕES AO DOMICÍLIO E SERVIÇO DE CATERING',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'BARES E DISCOTECAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CAMINHOS DE FERRO',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRANSPORTES TERRESTRES DE PASSAGEIROS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRANSP RODOVIÁRIOS DE MERCADORIAS (INCLUI CARGA E DESCARGA)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => ' TRANSPORTES POR OLEODUTOS E GASODUTOS (PIPELINES)',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRANSPORTES MARÍTIMOS E FLUVIAIS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TRIPULAÇÕES (TRANSPORTES AÉREOS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESSOAL DE APOIO E ASSISTÊNCIA A AEROPORTOS, EM TERRA',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CARGA E DESCARGA DE NAVIOS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESSOAL APOIO A PORTOS MARITIMOS (EXCLUI CARGAS E DESCARGAS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'GARAGENS E ESTAÇÕES DE SERVIÇO AUTOMÓVEL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'AGÊNCIAS DE VIAGEM E DE TURISMO, EMPRESAS DE RENT-A-CAR',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'DESPACHANTES, AGENTES TRANSITÁRIOS E ADUANEIROS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CORRESPONDÊNCIA E DOCUMENTOS (ENTREGAS)',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESSOAL DE RÁDIO, TELEVISÃO E AGÊNCIAS NOTICIOSAS',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'TELECOMUNICAÇÕES E CORREIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'BANCOS E INSTITUIÇÕES FINANCEIRAS E CRÉDITO',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SEGURADORAS E MEDIAÇÃO DE SEGUROS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'CONSULTORIA, AUDITORIA, ANÁLISE E INFORMÁTICA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'GABINETES DE ENGENHARIA E ARQUITECTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'AGÊNCIAS DE PERITAGENS E SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESCRITORIOS EM GERAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ACTIVIDADES JURIDICAS',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PUBLICIDADE, PROMOÇÃO E ORGANIZAÇÃO DE EVENTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'MEDIAÇÃO DE COMPRA E VENDA DE PROPRIEDADES',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'Reparação/manutenção máq. escritório e material informático',
                'risk' => 'Médio',
                'score' => 2,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ADMINISTRAÇÃO PÚBLICA / GOVERNO CENTRAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ADMINISTRAÇÃO PROVINCIAL / MUNICIPIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FORÇAS POLICIAIS E PARAMILITARES',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FORÇAS MILITARES',
                'risk' => 'Inaceitável',
                'score' => 150,
                'indicator_id' => 12,
            ],
            [
                'description' => 'BOMBEIROS E PROTECÇÃO CIVIL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'SEGURANÇA PRIVADA (EMPRESAS)',
                'risk' => 'Alto',
                'score' => 3,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ENSINO ESCOLAR (PROFESSORES E PESSOAL AUX. E ADMINISTRATIVO)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PROFESSORES DE EDUCAÇÃO FISICA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'ESCOLAS DE CONDUÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'FORMAÇÃO PROFISSIONAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => 'PESSOAL DE INFANTÁRIOS, LARES, ACÇÃO SOCIAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],
            [
                'description' => '85110 HOSPITAIS, CLINICAS, CENTROS DE SAÚDE, CONSULTÓRIOS MÉDICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 12,
            ],

            
        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorIndicatorType::where('description', $value['description'])->exists()) {
                IndicatorIndicatorType::create($value);
            }
        }
    }
}
