<?php

namespace Database\Seeders\nossaSeguros;

use App\Models\Indicator\IndicatorType as IndicatorIndicatorType;
use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class InsuranceTypeSeed extends Seeder
{
    public function run()
    {
        /**IndicatorType */
        $IndicatorType = [

            /**Tipo de Seguro */

            ['description' => 'Automóvel Frota', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],

            ['description' => 'Assistência Viagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'A.P. - Desporto', 'risk' => 'Baixo', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'Automóvel Individual', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],


            ['description' => 'seguro de Propriedade Comercial A.P. - Desporto', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial A.P. - Escolar', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Grupo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Individual', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Prestígio', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'AT - Conta de Outrem', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'AT - Prémio Fixo', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'Seguro Automóvel Automóvel Frota', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro Automóvel Automóvel Individual', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Aviação Aviação', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 8],
            ['description' => 'Seguro de Maritimo de Casco e Máquina Casco', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 8],
            ['description' => 'Seguros Maritimos Embarcações de Recreio', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial Máquinas Cascos', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Condomínio Multi Riscos Condominio', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial Multi Riscos Empresa', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de propriedade Residencial Multi Riscos Habitação', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial Multi Riscos Indústria', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de propriedade Residencial Multirriscos Habitação', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões Protecção à Família', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial R.C. - Exploração', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'seguro de Propriedade Comercial R.C. - Geral', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões R.C. - Profissional', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Saúde e Lesões Saúde AdvanceCare', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Automóveis T. M. - Rodoviário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 8],
            ['description' => 'Seguro de Vida Vida Crédito Individual', 'risk' => 'Muito Alto', 'score' => 20, 'indicator_id' => 8],
            ['description' => 'SEGURO DE AGRICULTURA (AVENÇA)', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 8],
            ['description' => 'SEGURO DE AGRICULTURA (GENÉRICO)', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 8],


            [
                'description' => 'CULTURA DE HORTÍCOLAS, RAÍZES E TUBÉRCULOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE CANA-DE-AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE TABACO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO…',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE FLORES E DE PLANTAS ORNAMENTAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRAS CULTURAS TEMPORÁRIAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'VITICULTURA (CULTURA DA VINHA)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE FRUTOS TROPICAIS E SUBTROPICAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE CITRINOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE POMÓIDEAS E PRUNÓIDEAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE FRUTOS DE CASCA RIJA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE OUTROS FRUTOS EM ÁRVORES E ARBUSTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OLIVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE OUTROS FRUTOS OLEAGINOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE PLANTAS DESTINADAS À PREPARAÇÃO DE BEBIDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE ESPECIARIAS, PLANTAS AROMÁTICAS, MEDICINAIS E FARMACÊUTICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRAS CULTURAS PERMANENTES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CULTURA DE MATERIAIS DE PROPAGAÇÃO VEGETATIVA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE BOVINOS PARA A PRODUÇÃO DE LEITE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE OUTROS BOVINOS (EXCEPTO P/PRODUÇÃO DE LEITE) E BÚFALOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE EQUINOS, ASININOS E MUARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE CAMELOS E CAMELÍDEOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE OVINOS E CAPRINOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'SUINICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'AVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'APICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CUNICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRIAÇÃO DE ANIMAIS DE COMPANHIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRA PRODUÇÃO ANIMAL NÃO ESPECIFICADA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'AGRICULTURA E PRODUÇÃO ANIMAL COMBINADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES RELACIONADAS COM AGRICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES RELACIONADAS COM PRODUÇÃO ANIMAL EXCEPTO SERVIÇOS DE VETERINÁRIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PREPARAÇÃO DE PRODUTOS AGRÍCOLAS PARA VENDA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PREPARAÇÃO E TRATAMENTO DE SEMENTES PARA PROPAGAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CAÇA E REPOVOAMENTO CINEGÉTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DOS SERVIÇOS RELACIONADAS COM CAÇA E REPOVOAMENTO CINEGÉTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'SILVICULTURA E EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DA CORTIÇA, RESINA E APANHA DE OUTROS PRODUTOS FLORESTAIS, EXCEPTO MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES RELACIONADAS C/SILVICULTURA E EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => '3111 PESCA MARÍTIMA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'APANHA DE ALGAS E DE OUTROS PRODUTOS DO MAR',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PESCA EM ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'APANHA DE PRODUTOS EM ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'AQUICULTURA EM ÁGUAS SALGADAS E SALOBRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'AQUICULTURA EM ÁGUAS DOCES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE HULHA (INCLUI ANTRACITE)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE LENHITE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE PETRÓLEO BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE GÁS NATURAL',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS DE FERRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE MINÉRIOS DE URÂNIO E DE TÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO E PREPARAÇÃO DE OUTROS MINÉRIOS METÁLICOS NÃO FERROSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE MÁRMORE E OUTRAS ROCHAS CARBONATADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE GRANITO ORNAMENTAL E ROCHAS SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE CALCÁRIO E CRÉ',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE GESSO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE ARDÓSIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAIBRO, AREIA E PEDRA BRITADA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE ARGILAS E CAULINO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE MINERAIS P/INDÚSTRIA QUÍMICA E FABRICAÇÃO ADUBOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DA TURFA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAL MARINHO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE SAL GEMA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE FELDSPATO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'EXTRACÇÃO DE OUTROS MINERAIS NÃO METÁLICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DOS SERVIÇOS RELACIONADOS COM A EXTRACÇÃO DE PETRÓLEO E GÁS, EXCEPTO A PROSPECÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRAS ACTIVIDADES DOS SERVIÇOS RELACIONADOS COM AS INDÚSTRIAS EXTRACTIVAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ABATE DE GADO (PRODUÇÃO DE CARNE)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ABATE DE AVES (PRODUÇÃO DE CARNE)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE PRODUTOS À BASE DE CARNE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PREPARAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CONGELAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CONSERVAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA EM AZEITE E OUTROS ÓLEOS VEGETAIS E OUTROS MOLHOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'SALGA, SECAGEM E OUTRAS ACTIVIDADES DE TRANSFORMAÇÃO DE PRODUTOS DA PESCA E AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PREPARAÇÃO E CONSERVAÇÃO DE BATATAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE SUMOS DE FRUTOS E PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CONGELAÇÃO DE FRUTOS E DE PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'SECAGEM E DESIDRATAÇÃO DE FRUTOS E DE PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE DOCES, COMPOTAS, GELEIAS E MARMELADA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'DESCASQUE E TRANSFORMAÇÃO DE FRUTOS DE CASCA RIJA COMESTÍVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PREPARAÇÃO E CONSERVAÇÃO DE FRUTOS E PRODUTOS HORTÍCOLAS POR OUTROS PROCESSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PRODUÇÃO DE ÓLEOS E GORDURAS ANIMAIS BRUTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PRODUÇÃO DE AZEITE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'PRODUÇÃO DE ÓLEOS VEGETAIS BRUTOS (EXCEPTO AZEITE)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'REFINAÇÃO DE AZEITE, ÓLEOS E GORDURAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MARGARINAS E DE GORDURAS ALIMENTARES SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE PRODUTOS FARMACÊUTICOS DE BASE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MEDICAMENTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE OUTRAS PREPARAÇÕES E DE ARTIGOS FARMACEUTICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE VIDRO PLANO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'MOLDAGEM E TRANSFORMAÇÃO DE VIDRO PLANO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE VIDRO DE EMBALAGEM',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CRISTALARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE FIBRAS DE VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => '23190 FABRICAÇÃO E TRANSFORMAÇÃO DE OUTRO VIDRO (INCLUI VIDRO TÉCNICO)',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE PRODUTOS CERÂMICOS REFRACTÁRIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE EMBALAGENS METÁLICAS PESADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE EMBALAGENS METÁLICAS LIGEIRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE PRODUTOS DE ARAME',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE CORRENTES METÁLICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE REBITES, PARAFUSOS E PORCAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MOTORES, GERADORES E TRANSFORMADORES ELÉCTRICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MATERIAL DE DISTRIBUIÇÃO E DE CONTROLO PARA INSTALAÇÕES ELÉCTRICAS DE ALTA TENSÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE MATERIAL DE DISTRIBUIÇÃO E DE CONTROLO PARA INSTALAÇÕES ELÉCTRICAS DE BAIXA TENSÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE CARROÇARIAS, REBOQUES E SEMI-REBOQUES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE EQUIPAMENTO ELÉCTRICO E ELECTRÓNICO PARA VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'FABRICAÇÃO DE OUTROS COMPONENTES E ACESSÓRIOS PARA VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'RECOLHA DE RESÍDUOS INERTES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'RECOLHA DE OUTROS RESÍDUOS NÃO PERIGOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'RECOLHA DE RESÍDUOS PERIGOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'INSTALAÇÃO ELÉCTRICA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'INSTALAÇÃO DE CANALIZAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'INSTALAÇÃO DE CLIMATIZAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRAS INSTALAÇÕES EM CONSTRUÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE ALIMENTOS PARA ANIMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE TABACO EM BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE CORTIÇA EM BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE CEREAIS, SEMENTES, LEGUMINOSAS, OLEAGINOSAS E OUTRAS MATÉRIAS-PRIMAS AGRÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE FLORES E PLANTAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE ANIMAIS VIVOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PELES E COURO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE VESTUÁRIO E ACESSÓRIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE ELECTRODOMÉSTICOS, APARELHOS DE RÁDIO E DE TELEVISÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE LOUÇAS EM CERÂMICA E EM VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PRODUTOS DE LIMPEZA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE ELECTRODOMÉSTICOS, APARELHOS DE RÁDIO E DE TELEVISÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE LOUÇAS EM CERÂMICA E EM VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => '46442 COMÉRCIO POR GROSSO DE PRODUTOS DE LIMPEZA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PERFUMES E DE PRODUTOS DE HIGIENE',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PRODUTOS FARMACÊUTICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE MÓVEIS PARA USO DOMÉSTICO, CARPETES, TAPETES E ARTIGOS DE ILUMINAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE RELÓGIOS E DE ARTIGOS DE OURIVESARIA E JOALHARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PRODUTOS PETROLÍFEROS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO COMBUSTÍVEIS SÓLIDOS, LÍQUIDOS E GASOSOS, NÃO DERIVADOS DO PETRÓLEO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE MINÉRIOS E DE METAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE MADEIRA EM BRUTO E DE PRODUTOS DERIVADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE MATERIAIS DE CONSTRUÇÃO (EXCEPTO MADEIRA) E EQUIPAMENTO SANITÁRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE FERRAGENS, FERRAMENTAS MANUAIS E ARTIGOS PARA CANALIZAÇÕES E AQUECIMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'COMÉRCIO POR GROSSO DE PRODUTOS QUÍMICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE AVALIAÇÃO DE RISCOS E DANOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE GESTÃO DE FUNDOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DOS ESTABELECIMENTOS DE SAÚDE COM INTERNAMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE PRÁTICA MÉDICA DE CLÍNICA GERAL, EM AMBULATÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE PRÁTICA MÉDICA DE CLÍNICA ESPECIALIZADA, EM AMBULATÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE MEDICINA DENTÁRIA E ODONTOLOGIA',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'LABORATÓRIOS DE ANÁLISES CLÍNICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE AMBULÂNCIAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES DE ENFERMAGEM',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'CENTROS DE RECOLHA E BANCOS DE ÓRGÃOS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'ACTIVIDADES TERMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
            [
                'description' => 'OUTRAS ACTIVIDADES DE SAÚDE HUMANA, NÃO ESPECIFICADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'indicator_id' => 8,
            ],
        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorIndicatorType::where('description', $value['description'])->exists()) {
                IndicatorIndicatorType::create($value);
            }
        }
    }
}
